import Head from "next/head";

export default function Home() {
  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>VoopBLOGue</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        skoopa tonik
      </div>
    </div>
  );
}
